# Generated by Django 4.0.6 on 2022-07-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date_published', models.DateField(verbose_name='date published')),
                ('live_site', models.URLField(verbose_name='live site')),
                ('github', models.URLField(verbose_name='github link')),
                ('color_scheme', models.ManyToManyField(to='main_app.colorscheme')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex', models.CharField(default='#000000', max_length=7)),
                ('color_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.colorscheme')),
            ],
        ),
    ]
