# Generated by Django 4.0.6 on 2022-07-10 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_project_color_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_scheme',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.colorscheme'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color_scheme',
            field=models.ManyToManyField(blank=True, to='main_app.colorscheme'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_published',
            field=models.DateField(blank=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, verbose_name='github link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_site',
            field=models.URLField(blank=True, verbose_name='live site'),
        ),
    ]
