# Generated by Django 4.0.6 on 2022-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_color_color_scheme_alter_project_color_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
