# Generated by Django 4.0.6 on 2022-07-11 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_colorscheme_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorscheme',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='color_scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.colorscheme'),
            preserve_default=False,
        ),
    ]
