# Generated by Django 4.0.6 on 2022-07-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_colorscheme_color_color_color_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_scheme',
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color',
            field=models.ManyToManyField(blank=True, to='main_app.color'),
        ),
    ]
